"""create programs table

Revision ID: 2e29788e3d2a
Revises: 5d38be7cfc5d
Create Date: 2026-06-26 11:38:44.992264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e29788e3d2a'
down_revision: Union[str, Sequence[str], None] = '5d38be7cfc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('tier', sa.Enum('reach', 'match', 'likely', name='tier'), nullable=False),
    sa.Column('status', sa.Enum('researching', 'drafting', 'submitted', 'interview', 'decision', name='programstatus'), nullable=False),
    sa.Column('app_fee', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_user_id'), 'programs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programs_user_id'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
