"""add recommenders and program_recommenders

Revision ID: 5200ae9c068c
Revises: 8b26887526c7
Create Date: 2026-06-27 08:32:00.966216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5200ae9c068c'
down_revision: Union[str, Sequence[str], None] = '8b26887526c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommenders_user_id'), 'recommenders', ['user_id'], unique=False)
    op.create_table('program_recommenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommender_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('asked', 'confirmed', 'submitted', name='recommenderstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['recommender_id'], ['recommenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_recommenders_program_id'), 'program_recommenders', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_recommenders_recommender_id'), 'program_recommenders', ['recommender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_recommenders_recommender_id'), table_name='program_recommenders')
    op.drop_index(op.f('ix_program_recommenders_program_id'), table_name='program_recommenders')
    op.drop_table('program_recommenders')
    op.drop_index(op.f('ix_recommenders_user_id'), table_name='recommenders')
    op.drop_table('recommenders')
    # ### end Alembic commands ###
