"""add url to documents

Revision ID: 61b9ccfe8366
Revises: 5f2e6eac99ef
Create Date: 2026-06-27 16:24:40.552664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b9ccfe8366'
down_revision: Union[str, Sequence[str], None] = '5f2e6eac99ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'url')
    # ### end Alembic commands ###
