"""create requirements table

Revision ID: a290203c936e
Revises: 2e29788e3d2a
Create Date: 2026-06-26 11:43:43.991993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a290203c936e'
down_revision: Union[str, Sequence[str], None] = '2e29788e3d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('sop', 'cv', 'transcript', 'gre', 'writing_sample', 'fee', 'other', name='requirementkind'), nullable=False),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'done', 'waived', name='requirementstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_program_id'), 'requirements', ['program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirements_program_id'), table_name='requirements')
    op.drop_table('requirements')
    # ### end Alembic commands ###
