"""add outreach_contacts

Revision ID: eab5b3f5ac5b
Revises: 5200ae9c068c
Create Date: 2026-06-27 08:37:27.029876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab5b3f5ac5b'
down_revision: Union[str, Sequence[str], None] = '5200ae9c068c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('contacted_on', sa.Date(), nullable=True),
    sa.Column('response', sa.Enum('none', 'positive', 'negative', 'meeting_scheduled', name='outreachresponse'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_contacts_program_id'), 'outreach_contacts', ['program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_contacts_program_id'), table_name='outreach_contacts')
    op.drop_table('outreach_contacts')
    # ### end Alembic commands ###
